routes/web.php
<?php

use App\Http\Controllers\ProjectsController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','WelcomeController@index');


Auth::routes();

Route::middleware(['auth','employee','manager'])->group(function(){
      // Route::get('/users','UsersController@index')->name('users.index') ;
      Route::resource('users','UsersController')->except('bestEmployee');
      Route::get('users/hello', 'UsersController@bestEmployee')->name('bestEmployee');

});
Route::middleware(['auth'])->group(function(){
      Route::resource('projects', 'ProjectsController')->except('detail');
Route::get('projects/detail/{user}', 'ProjectsController@detail')->name('projects.detail');

Route::put('projects/status/{project}', 'StatusController@projectStatus')->name('projects.status');
Route::get('projects/status/{project}', 'StatusController@projectFinalStatus')->name('projects.final.status');
Route::put('tasks/status/{task}', 'StatusController@taskStatus')->name('tasks.status');
Route::get('tasks/status/{task}', 'StatusController@taskFinalStatus')->name('tasks.final.status');


Route::resource('tasks','TasksController')->except('create','detailing');
// Route::get('tasks/{user}', 'TasksController@show')->name('tasks.show');
Route::get('tasks/details/{user}', 'TasksController@details')->name('tasks.details');
Route::get('tasks/{user}/create', 'TasksController@create')->name('tasks.create');
Route::get('tasks/{task}/reassign', 'TasksController@reassign')->name('tasks.reassign');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
    protected $fillable = [
        'title' , 'overview' ,'status'
    ];

    // public function users()
    // {
    //     return $this->hasMany(User::class);
    // }

    public function users()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }
    public function tasks()
    {
        return $this->hasMany(Task::class);
    }



}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Projects\CreateProjectRequest;
use App\User;
use App\Project;
use Illuminate\Http\Request;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //  dd(auth()->user()->id);
        $user = auth()->user();
        $projects = Project::all();
        if($user->isAdmin())
        {
            return view('projects.index', compact(['projects']));
        }
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users =  User::where('assigned', '0')->get();
        return view('projects.create', compact(['users']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, User $user)
    {
        //
        // dd($request->manager_id);
        $project= Project::create([
            'title'=>$request->title,
            'overview'=> $request->overview,
        ]);

        $project->users()->attach($request->manager_id);
        $project->users()->attach($request->team);
        
        $manager_id =$request->manager_id;
        $team_members = $request->team;
        
        User::where('id', $manager_id)->update(['assigned'=>'1', 'role'=>'Project Manager']);
        User::whereIn('id', $team_members)->update(['assigned'=>'1']);

        session()->flash('success','Project Created Successfully');
        return redirect(route('projects.index'));
    }

    // public function updateUser(Request $request, User $user)
    // {
         
    //     dd($request->manager_id);
    // }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {   
        $project = $project;
        $users = $project->users()->get();
        return view('projects.show', compact([
                'users','project'
            ]));
    }
    public function detail(User $user)
    {
        $project_details = $user->project()->get();
        $project = $project_details;
        // dd($project);
        if (!$project_details->isEmpty())
        {
            // dd($project_details);
            $project = $project_details[0];
            $users = $project->users()->get();
            return view('projects.show', compact([
                'users', 'project'
            ]));
        }
        else{
            $project = [];
            return view('projects.show', compact([
             'project'
        ]));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }

}

resources/views/projects/create.blade.php
@extends('layouts.app')
@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    
@endsection
@section('content')
    <div class="card">
        <div class="card-header">Add Project</div>
        <div class="card-body">
            <form action="{{ route('projects.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                            value="{{old('title')}}"
                            class="form-control @error('title') is-invalid @enderror"
                            name="title" id="title">
                    @error('title')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="overview">Overview</label>
                    <input id="overview" type="hidden" name="overview">
                    <trix-editor input="overview"></trix-editor>
                    <!-- <textarea class="form-control @error('overview') is-invalid @enderror"
                            name="overview" id="overview" rows="4">{{old('overview')}}</textarea> -->
                    @error('overview')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="manager">Project Manager</label>
                    <select name="manager_id" id="manager_id" class="form-control">
                        @foreach($users as $user)
                            <option value="{{$user->id}}">{{$user->name}}</option>
                        @endforeach
                    </select>
                    @error('users')
                        <p class="text-danger font-weight-light">{{$errors->first('users')}}</p>
                    @enderror    
                </div>
                <div class="form-group">
                    <label for="team[]">Team</label>
                    <select name="team[]" id="team" class="form-control select2" multiple>
                        @foreach($users as $user)
                            <option value="{{$user->id}}">{{$user->name}}</option>
                        @endforeach
                    </select>
                    @error('users')
                        <p class="text-danger font-weight-light">{{$errors->first('users')}}</p>
                    @enderror    
                </div>
                <div class="form-group">
                    <button class="btn btn-success" type="submit">Add Project</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('page-level-scripts')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script>
        flatpickr("#published_at", {
            enableTime: true
        });
    $(document).ready(function(){
            $('.select2').select2();
        });
    </script>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex justify-content-end mb-3">
            <a href="{{ route('projects.create') }}"  class="btn btn-primary">New Project</a>
    </div> 

    <div class="card">
        <div class="card-header">Projects</div>

        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <th>Name</th>
                    <th>Status</th>
                    <th>Details</th>
                    <th>Action</th>
                </thead>
                <tbody>
                    @foreach($projects as $project)
                        <tr>
                            <td>
                                {{$project->title}}
                            </td>
                            <td>
                                {{$project->status}}
                            </td>
                            <td>
                                <a href="{{route('projects.show', $project->id)}}">Details</a>
                            </td>
                            <td>
                                @if($project->status === 'Done')
                                <a href="{{route('projects.final.status', $project->id)}}" class="btn btn-outline-danger">Completed</a>
                                @endif
                                @if(!($project->status === 'Completed'))
                                <a href="" class="btn btn-outline-success">Reassign</a>
                                @endif
                            </td>
                        </tr>
                      @endforeach  
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('page-level-styles')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
@endsection

@section('content')
<div class="card">

@if($project)
    <div class="card-header">
    <div class="row">
    <div class="col-md-9"><h5 class="text-primary text-align-center p-2">Project Details</h5></div>
    <div class="col-md-3">
        @if($project->status === 'Completed')
            <h5 class="text-danger text-right p-2">Completed</h5>
        @endif
    </div>
    </div>
    </div> 
    <div class="card-body">
        <h2>{{$project->title}}</h2>
        <br>
        <h4>Overview</h4>
        <p>{!!$project->overview!!}</p>
        <h4>Project Manager</h4>
        @foreach($users as $user)
        @if($user->role === 'Project Manager')
                <p>{{$user->name}}</p>
        @endif
        @endforeach
        <h4>Team Members</h4>
        <ul>
        @foreach($users as $user)
        @if(!($user->role === 'Project Manager'))
                <li>{{$user->name}}</li>
        @endif
        @endforeach
        </ul>
        @if(auth()->user()->role === 'Project Manager')
            <a href="{{route('tasks.index')}}" class="btn btn-primary">Task Details</a>
        @endif
        @if(auth()->user()->role === 'Employee')
        <a href="{{route('tasks.details',auth()->user()->id)}}" class="btn btn-primary">Task Details</a>
        @endif

        <br>
        <br>    
        
        @if(!($project->status === 'Completed'))
        <h4>Status</h4>
        <form action="{{route('projects.status', $project->id)}}" method="POST">
            @csrf   
            @method('PUT')
            <button type="submit" class="btn {{$project->status ==='Done' ? 'text-success' : ''}}" onclick="addClassOnClick(this)" value="Done">
            <div class="form-check">
                <input class="form-check-input" type="hidden" name="status" id="status" value="Done">
                <label class="form-check-label"><i class="fa fa-check">Done</i>
            </div>
            </button>
        </form>

        <form action="{{route('projects.status', $project->id)}}" method="POST">
            @csrf   
            @method('PUT')
            <button type="submit" class="btn {{$project->status ==='onGoing' ? 'text-success' : ''}}" onclick="addClassOnClick(this)" value="onGoing">
            <div class="form-check">
                <input class="form-check-input" type="hidden" name="status" id="status" value="onGoing">
                <label class="form-check-label"><i class="fa fa-check">onGoing</i>
            </div>
            </button>
        </form>
        
        <form action="{{route('projects.status', $project->id)}}" method="POST">
            @csrf   
            @method('PUT')
            <button type="submit" class="btn {{$project->status ==='Give Up' ? 'text-success' : ''}}" onclick="addClassOnClick(this)" value="Give Up">
            <div class="form-check">
                <input class="form-check-input" type="hidden" name="status" id="status" value="Give Up">
                <label class="form-check-label"><i class="fa fa-check">Give Up</i>
            </div>
            </button>
        </form>

        @endif
    @else
    <h3 class="text-secondary p-5">You are not a part of any project as of now</h3>

    </div>
    </div>
@endif

<script>
    function addClassOnClick(button){
        $(button).addClass("text-success")
    }
</script>
@endsection