routes/web.php
<?php

use App\Http\Controllers\ProjectsController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','WelcomeController@index');


Auth::routes();

Route::middleware(['auth','employee','manager'])->group(function(){
      // Route::get('/users','UsersController@index')->name('users.index') ;
      Route::resource('users','UsersController')->except('bestEmployee');
      Route::get('users/hello', 'UsersController@bestEmployee')->name('bestEmployee');

});
Route::middleware(['auth'])->group(function(){
      Route::resource('projects', 'ProjectsController')->except('detail');
Route::get('projects/detail/{user}', 'ProjectsController@detail')->name('projects.detail');

Route::put('projects/status/{project}', 'StatusController@projectStatus')->name('projects.status');
Route::get('projects/status/{project}', 'StatusController@projectFinalStatus')->name('projects.final.status');
Route::put('tasks/status/{task}', 'StatusController@taskStatus')->name('tasks.status');
Route::get('tasks/status/{task}', 'StatusController@taskFinalStatus')->name('tasks.final.status');


Route::resource('tasks','TasksController')->except('create','detailing');
// Route::get('tasks/{user}', 'TasksController@show')->name('tasks.show');
Route::get('tasks/details/{user}', 'TasksController@details')->name('tasks.details');
Route::get('tasks/{user}/create', 'TasksController@create')->name('tasks.create');
Route::get('tasks/{task}/reassign', 'TasksController@reassign')->name('tasks.reassign');

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['project_id', 'user_id', 'title', 'description'];
    

    public function project()
    {
        return $this->belongsTo(Project::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\Task;
use App\User;
use Illuminate\Http\Request;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = auth()->user();
        // dd($user);
        $project_details = $user->project()->get();
        $project = $project_details[0];
        $users = $project->users()->where('role','employee')->get();
        // $users = $users_details[0];
        return view('tasks.index', compact(['project','users']));
    }

    public function details(User $user)
    {
        // dd($user);
        $tasks = Task::where('user_id', $user->id)->get();
        // dd($tasks);
        return view('tasks.details', compact(['tasks']));
    }
    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(User $user)
    {
        return view('tasks.create', compact(['user']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->user_id);
        $user_details = User::where('id', $request->user_id)->get();
        $user = $user_details[0];
        $project = $user->project()->get();
        $project_id = $project[0]->id;

        $project= Task::create([
            'project_id'=>$project_id,
            'user_id'=>$user->id,
            'title'=>$request->title,
            'description'=> $request->description,
        ]);

        $task_count = $user->tasks_count;
        $user->updateTasksCount($task_count, $user->id);

        session()->flash('success','Task Reassigned Successfully');
        return redirect(route('tasks.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        // dd($task);
        $user_details = User::where('id', $task->user_id)->get();
        $user = $user_details[0];
        return view('tasks.show', compact(['task', 'user']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(User $task)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        //
    }
    public function reassign(Task $task)
    {
        $project_details = $task->project()->get();
        $project = $project_details[0];
        $users = $project->users()->get();
        // dd($users);
        return view('tasks.reassign', compact(['task', 'users']));
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')
@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    
@endsection

@section('content')
<div class="card">
    <div class="card-header">Add Task</div>
    <div class="card-body">
        <form action="{{route('tasks.store')}}" method="POST">
            @csrf   
            <input type="hidden" value="{{$user->id}}" name="user_id">
            <div class="form-group">
                    <label for="name">Assign To</label>
                    <input type="text"
                            value="{{$user->name}}"
                            class="form-control @error('name') is-invalid @enderror"
                            name="name" id="name">
                    @error('name')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
            </div>   

            <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                            value="{{old('title')}}"
                            class="form-control @error('title') is-invalid @enderror"
                            name="title" id="title">
                    @error('title')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <input id="description" type="hidden" name="description">
                    <trix-editor input="description"></trix-editor>
                    <!-- <textarea class="form-control @error('description') is-invalid @enderror"
                            name="description" id="description" rows="4">{{old('description')}}</textarea> -->
                    @error('description')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>  

                <div class="form-group">
                    <button class="btn btn-success" type="submit">Add Task</button>
                </div>
        </form>
    </div>
</div>
@endsection

@section('page-level-scripts')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script>
        flatpickr("#published_at", {
            enableTime: true
        });
    $(document).ready(function(){
            $('.select2').select2();
        });
    </script>
@endsection

resources/views/tasks/details.blade.php
@extends('layouts.app')

@section('content')
    @if(auth()->user()->role === 'Project Manager')
    <div class="d-flex justify-content-end mb-3">
    <a href="{{ route('tasks.create', $tasks[0]->user_id) }}"  class="btn btn-primary">Assign Task</a>
    </div> 
    @endif
    <div class="card">
        <div class="card-header">Tasks</div>
    @if(!$tasks->isEmpty())
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <th>Name</th>
                    <th>Status</th>
                    <th>Details</th>
                    @if(auth()->user()->role === 'Project Manager')
                    <th>Action</th>
                    @endif
                </thead>
                <tbody>
                    @foreach($tasks as $task)
                        <tr>
                            <td>
                                {{$task->title}}
                            </td>
                            <td>
                                {{$task->status}}
                            </td>
                            <td>
                                <a href="{{route('tasks.show', $task->id)}}">Details</a>
                            </td>
                           
                            @if(auth()->user()->role === 'Project Manager') 
                            <td>
                                @if($task->status === 'Done')
                                <a href="{{route('tasks.final.status', $task->id)}}" class="btn btn-outline-danger">Completed</a>
                                @endif
                                @if(!($task->status === 'Completed'))
                                <a href="{{route('tasks.reassign', $task->id)}}" class="btn btn-outline-success">Reassign</a>
                                @endif
                            </td>
                            @endif
                        </tr>
                      @endforeach  
                </tbody>
            </table>
            @else
            <h3 class="text-secondary p-5">No Tasks</h3>
        </div>
        @endif
    </div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="card">
        <div class="card-header">Task Details</div>

        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <th>Name</th>
                    <th>Project Name</th>
                    <th>Tasks Assigned</th>
                    <th>Action</th>
                    <th>Details</th>
                </thead>
                <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>
                                {{$user->name}}
                            </td>
                            <td>
                                {{$project->title}}
                            </td>
                            <td>
                                {{$user->tasks_count}}
                            </td>
                            <td>
                                <a href="{{ route('tasks.create', $user->id) }}" class="btn btn-outline-primary">Assign Task</a>
                            </td>
                            <td>
                             @if($user->tasks_count)
                            <a href="{{ route('tasks.details', $user->id)}}" class="btn btn-outline-danger">Details</a>
                            @endif
                            </td>
                            
                        </tr>
                      @endforeach  
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/tasks/reassign.blade.php
@extends('layouts.app')
@section('page-level-styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
    
@endsection

@section('content')
<div class="card">
    <div class="card-header">Reassign Task</div>
    <div class="card-body">
        <form action="{{route('tasks.store')}}" method="POST">
            @csrf   
            <div class="form-group">
                    <label for="name">Assign to</label>
                    <select name="user_id" id="user_id" class="form-control">
                        @foreach($users as $user)
                            @if($user->role === 'Employee')
                                <option value="{{$user->id}}">{{$user->name}}</option>
                            @endif
                        @endforeach
                    </select>
                    @error('users')
                        <p class="text-danger font-weight-light">{{$errors->first('users')}}</p>
                    @enderror    
                </div> 

            <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text"
                            value="{{$task->title}}"
                            class="form-control @error('title') is-invalid @enderror"
                            name="title" id="title">
                    @error('title')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <input id="description" type="hidden" name="description" value="{{$task->description}}">
                    <trix-editor input="description"></trix-editor>
                    <!-- <textarea class="form-control @error('description') is-invalid @enderror"
                            name="description" id="description" rows="4">{{old('description')}}</textarea> -->
                    @error('description')
                        <p class="text-danger">{{$message}}</p>
                    @enderror
                </div>  

                <div class="form-group">
                    <button class="btn btn-success" type="submit">Reassign Task</button>
                </div>
        </form>
    </div>
</div>
@endsection

@section('page-level-scripts')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script>
        flatpickr("#published_at", {
            enableTime: true
        });
    $(document).ready(function(){
            $('.select2').select2();
        });
    </script>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('page-level-styles')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
@endsection

@section('content')
<div class="card">
<div class="card-header">
<div class="row">
<div class="col-md-9"><h5 class="text-primary text-align-center p-2">Task Details</h5></div>
<div class="col-md-3">
    @if($task->status === 'Completed')
        <h5 class="text-danger text-right p-2">Completed</h5>
    @endif
</div>
</div>
</div> 
<div class="card-body">
    <h2>{{$task->title}}</h2>
    <br>
    <h4>Description</h4>
    <p>{!!$task->description!!}</p>
    
    @if($user->id === auth()->user()->id ) 
    @if(!($task->status === 'Completed'))
    <h4>Status</h4>
    <form action="{{route('tasks.status', $task->id)}}" method="POST">
        @csrf   
        @method('PUT')
        <button type="submit" class="btn {{$task->status ==='Done' ? 'text-success' : ''}}" onclick="addClassOnClick(this)" value="Done">
        <div class="form-check">
            <input class="form-check-input" type="hidden" name="status" id="status" value="Done">
            <label class="form-check-label"><i class="fa fa-check">Done</i>
        </div>
        </button>
    </form>

    <form action="{{route('tasks.status', $task->id)}}" method="POST">
        @csrf   
        @method('PUT')
        <button type="submit" class="btn {{$task->status ==='onGoing' ? 'text-success' : ''}}" onclick="addClassOnClick(this)" value="onGoing">
        <div class="form-check">
            <input class="form-check-input" type="hidden" name="status" id="status" value="onGoing">
            <label class="form-check-label"><i class="fa fa-check">onGoing</i>
        </div>
        </button>
    </form>
    
    <form action="{{route('tasks.status', $task->id)}}" method="POST">
        @csrf   
        @method('PUT')
        <button type="submit" class="btn {{$task->status ==='Give Up' ? 'text-success' : ''}}" onclick="addClassOnClick(this)" value="Give Up">
        <div class="form-check">
            <input class="form-check-input" type="hidden" name="status" id="status" value="Give Up">
            <label class="form-check-label"><i class="fa fa-check">Give Up</i>
        </div>
        </button>
    </form>

    @endif
    @endif
</div>
</div>

<script>
    function addClassOnClick(button){
        $(button).addClass("text-success")
    }
</script>
@endsection